import { FileText, Download, Share2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { alerts, actions } from '@/data/mock';
import { RiskBadge } from '@/components/shared/RiskBadge';

export default function Reports() {
  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border px-6 py-4 flex items-center justify-between sticky top-0 z-10 bg-background/95 backdrop-blur-sm">
        <div>
          <h1 className="text-base font-semibold text-foreground flex items-center gap-2">
            <FileText className="w-4 h-4 text-primary" />
            Reports
          </h1>
          <p className="text-[11px] font-mono text-muted-foreground mt-0.5">Stakeholder outputs · auto-generated</p>
        </div>
        <div className="flex gap-2">
          <Button size="sm" variant="outline" className="gap-1.5 text-xs">
            <Share2 className="w-3.5 h-3.5" /> Share link
          </Button>
          <Button size="sm" className="gap-1.5 text-xs">
            <Download className="w-3.5 h-3.5" /> Export PDF
          </Button>
        </div>
      </header>

      <div className="p-6 max-w-3xl mx-auto space-y-8">
        {/* Brief header */}
        <div className="bg-card border border-border rounded-md p-6 space-y-2">
          <div className="flex items-center justify-between">
            <div>
              <p className="data-label">Weekly Early-Warning Brief</p>
              <h2 className="text-lg font-semibold text-foreground mt-1">Week of 17–23 February 2026</h2>
              <p className="text-xs text-muted-foreground">Generated by PHES Model v2.4 · Access controlled · Privacy applied</p>
            </div>
            <div className="text-right">
              <div className="font-mono text-3xl font-medium text-[hsl(var(--risk-high))]">3</div>
              <div className="data-label">open alerts</div>
            </div>
          </div>
        </div>

        {/* Risk summary */}
        <section className="space-y-3">
          <h3 className="text-sm font-semibold text-foreground border-b border-border pb-2">Rising risks this week</h3>
          {alerts.filter(a => a.status === 'open').map(alert => (
            <div key={alert.id} className="flex items-start justify-between p-3 bg-card border border-border rounded-md">
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <RiskBadge level={alert.riskLevel} />
                  <span className="text-xs font-medium text-foreground">{alert.type}</span>
                </div>
                <p className="text-[11px] text-muted-foreground">{alert.regionName} · {alert.timeWindow} · {alert.affectedPopulation.toLocaleString()} pop.</p>
              </div>
              <div className="text-right">
                <div className="font-mono text-lg font-medium text-foreground">{alert.probability}%</div>
                <div className="data-label">probability</div>
              </div>
            </div>
          ))}
        </section>

        {/* Action summary */}
        <section className="space-y-3">
          <h3 className="text-sm font-semibold text-foreground border-b border-border pb-2">Actions this week</h3>
          {actions.map(action => {
            const pct = Math.round((action.completedSteps.length / action.playbook.length) * 100);
            return (
              <div key={action.id} className="flex items-center justify-between p-3 bg-card border border-border rounded-md">
                <div>
                  <p className="text-xs font-medium text-foreground mb-0.5">{action.title}</p>
                  <p className="text-[10px] text-muted-foreground">{action.assignedTeam} · Due {action.dueDate}</p>
                </div>
                <div className="flex items-center gap-3">
                  <div className="text-right">
                    <span className="font-mono text-xs text-foreground">{pct}%</span>
                    <div className="data-label">complete</div>
                  </div>
                  <span className={`text-[10px] font-mono px-1.5 py-0.5 rounded-sm border capitalize ${
                    action.status === 'active' ? 'text-primary border-primary/30 bg-primary/10' :
                    action.status === 'blocked' ? 'text-[hsl(var(--risk-moderate))] border-[hsl(var(--risk-moderate)/0.3)] bg-[hsl(var(--risk-moderate)/0.08)]' :
                    'text-muted-foreground border-border'
                  }`}>
                    {action.status}
                  </span>
                </div>
              </div>
            );
          })}
        </section>

        {/* KPIs */}
        <section className="space-y-3">
          <h3 className="text-sm font-semibold text-foreground border-b border-border pb-2">KPI summary</h3>
          <div className="grid grid-cols-3 gap-3">
            {[
              { label: 'Lead time gained', value: '14.2 days', sub: 'vs reactive response' },
              { label: 'Alerts resolved', value: '2 / 5', sub: 'this period' },
              { label: 'Avg response speed', value: '18 hrs', sub: 'alert → action' },
            ].map(kpi => (
              <div key={kpi.label} className="bg-card border border-border rounded-md p-3">
                <div className="data-label mb-1">{kpi.label}</div>
                <div className="font-mono text-xl font-medium text-foreground">{kpi.value}</div>
                <div className="text-[10px] text-muted-foreground">{kpi.sub}</div>
              </div>
            ))}
          </div>
        </section>
      </div>
    </div>
  );
}
